// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatRefreshController from "./chat_refresh_controller"
application.register("chat-refresh", ChatRefreshController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import CommentsController from "./comments_controller"
application.register("comments", CommentsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import PrivateChatroomSubscriptionController from "./private_chatroom_subscription_controller"
application.register("private-chatroom-subscription", PrivateChatroomSubscriptionController)

import WorkoutIndexController from "./workout_index_controller"
application.register("workout-index", WorkoutIndexController)
