// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import CommentsController from "./comments_controller"
application.register("comments", CommentsController)

import ContentLoaderController from "./content_loader_controller"
application.register("content-loader", ContentLoaderController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import WorkoutIndexController from "./workout_index_controller"
application.register("workout-index", WorkoutIndexController)
